name: Manually

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 6

     - name: Changed files
        run: |
          echo 2
          git diff --name-only HEAD~2
          echo 5
          git diff --name-only HEAD~5

          # This will fail because not enough commits
          #echo 6
          #git diff --name-only HEAD~6

